export const allElements = [
  {
    elementID: "heightSlider",
    eventType: "input",
    inputType: "range",
    stateKey: ["contentSettings", "height"],
  },
  {
    elementID: "widthSlider",
    eventType: "input",
    inputType: "range",
    stateKey: ["contentSettings", "width"],
  },
  {
    elementID: "bgColor",
    eventType: "input",
    inputType: "color",
    stateKey: ["contentSettings", "backgroundColor"],
  },
  {
    elementID: "textArea",
    eventType: "input",
    inputType: "textarea",
    stateKey: ["contentSettings", "content"],
  },
  {
    elementID: "fontSizeSlider",
    eventType: "input",
    inputType: "range",
    stateKey: ["textSettings", "fontsize"],
  },
  {
    elementID: "boldCheckbox",
    eventType: "change",
    inputType: "checkbox",
    stateKey: ["textSettings", "bold"],
  },
  {
    elementID: "italicCheckbox",
    eventType: "change",
    inputType: "checkbox",
    stateKey: ["textSettings", "italic"],
  },
  {
    elementID: "underlineCheckbox",
    eventType: "change",
    inputType: "checkbox",
    stateKey: ["textSettings", "underline"],
  },
  {
    elementID: "strikethroughCheckbox",
    eventType: "change",
    inputType: "checkbox",
    stateKey: ["textSettings", "strikethrough"],
  },
  {
    elementID: "fontFamilySelect",
    eventType: "change",
    inputType: "select",
    stateKey: ["textSettings", "fontFamily"],
  },
  {
    elementID: "fontColor",
    eventType: "input",
    inputType: "color",
    stateKey: ["textSettings", "fontColor"],
  },
  {
    elementID: "textAlignLeft",
    eventType: "change",
    inputType: "radio",
    stateKey: ["textSettings", "textAlign"],
  },
  {
    elementID: "textAlignCenter",
    eventType: "change",
    inputType: "radio",
    stateKey: ["textSettings", "textAlign"],
  },
  {
    elementID: "textAlignRight",
    eventType: "change",
    inputType: "radio",
    stateKey: ["textSettings", "textAlign"],
  },
  {
    elementID: "topBorderCheckbox",
    eventType: "change",
    inputType: "checkbox",
    stateKey: ["borderSettings", "topBorder"],
  },
  {
    elementID: "rightBorderCheckbox",
    eventType: "change",
    inputType: "checkbox",
    stateKey: ["borderSettings", "rightBorder"],
  },
  {
    elementID: "bottomBorderCheckbox",
    eventType: "change",
    inputType: "checkbox",
    stateKey: ["borderSettings", "bottomBorder"],
  },
  {
    elementID: "leftBorderCheckbox",
    eventType: "change",
    inputType: "checkbox",
    stateKey: ["borderSettings", "leftBorder"],
  },
  {
    elementID: "borderTypeSelect",
    eventType: "change",
    inputType: "select",
    stateKey: ["borderSettings", "borderType"],
  },
  {
    elementID: "borderSizeSlider",
    eventType: "input",
    inputType: "range",
    stateKey: ["borderSettings", "borderSize"],
  },
  {
    elementID: "borderColor",
    eventType: "input",
    inputType: "color",
    stateKey: ["borderSettings", "borderColor"],
  },
  {
    elementID: "borderRadiusSlider",
    eventType: "input",
    inputType: "range",
    stateKey: ["borderSettings", "borderRadius"],
  },
  {
    elementID: "shadowCheckbox",
    eventType: "change",
    inputType: "checkbox",
    stateKey: ["borderSettings", "shadow"],
  },
  {
    elementID: "insetShadowCheckbox",
    eventType: "change",
    inputType: "checkbox",
    stateKey: ["borderSettings", "insetShadow"],
  },
  {
    elementID: "shadowShiftRightSlider",
    eventType: "input",
    inputType: "range",
    stateKey: ["borderSettings", "shadowShiftRight"],
  },
  {
    elementID: "shadowShiftDownSlider",
    eventType: "input",
    inputType: "range",
    stateKey: ["borderSettings", "shadowShiftDown"],
  },
  {
    elementID: "shadowSpreadSlider",
    eventType: "input",
    inputType: "range",
    stateKey: ["borderSettings", "shadowSpread"],
  },
  {
    elementID: "shadowBlurSlider",
    eventType: "input",
    inputType: "range",
    stateKey: ["borderSettings", "shadowBlur"],
  },
  {
    elementID: "shadowOpacitySlider",
    eventType: "input",
    inputType: "range",
    stateKey: ["borderSettings", "shadowOpacity"],
  },
  {
    elementID: "shadowColor",
    eventType: "input",
    inputType: "color",
    stateKey: ["borderSettings", "shadowColor"],
  },
  {
    elementID: "leftPosition",
    eventType: "input",
    inputType: "range",
    stateKey: ["contentSettings", "leftPosition"],
  },
  {
    elementID: "topPosition",
    eventType: "input",
    inputType: "range",
    stateKey: ["contentSettings", "topPosition"],
  },
  {
    elementID: "writingModeSelect",
    eventType: "change",
    inputType: "select",
    stateKey: ["textSettings", "writingMode"],
  },
  {
    elementID: "wordSpacingSlider",
    eventType: "input",
    inputType: "range",
    stateKey: ["textSettings", "wordSpacing"],
  },
  {
    elementID: "lineHeightSlider",
    eventType: "input",
    inputType: "range",
    stateKey: ["textSettings", "lineHeight"],
  },
];
